update runit: input parameter changed to starting number

diff --git a/runit b/runit
--- a/runit
+++ b/runit
@@ -1,31 +1,37 @@
 #!/bin/bash
 #
 
-s_VERSION="1.6"
+s_VERSION="1.7"
 EXE_NAME="`realpath $0`"
 EXE_BASE="`basename ${EXE_NAME}`"
 EXE_DIR="`dirname ${EXE_NAME}`"
+START_LINE_MIN="1"
 b_VERBOSE=0
 b_DEBUG=0
 
 COLOR="${EXE_DIR}/asc"
 
-SKIP_LINES=0
+START_LINE="${START_LINE_MIN}"
 if [[ "$1" != "" ]]; then 
     if [[ ! -f "$1" ]]; then  
         if [[ "$1" =~ ^[0-9]+$ ]]; then 
-            SKIP_LINES="$1"
+            START_LINE="$1"
         fi 
         shift 1
     fi
 fi
+
+if [[ ${START_LINE} -lt ${START_LINE_MIN} ]]; then 
+    printf '\nERROR-00: %s from number %d is inavlid!, first valid number is %d\n' "${EXE_NAME}" ${START_LINE} ${START_LINE_MIN}
+    exit 1 
+fi 
 
 N_ERROR=0
 N_LINES=0
 while read line
 do
     let N_LINES+=1
-    if [[ ${N_LINES} -gt ${SKIP_LINES} ]]; then
+    if [[ ${N_LINES} -ge ${START_LINE} ]]; then
         ${COLOR} CYAN
         printf '\n=========================== '
         ${COLOR} YELLOW
@@ -77,8 +83,10 @@ do
         	fi 
         fi 
     else
-	${COLOR} RED
-	printf ' %4d: SKIP: \"%s\"\n' ${N_LINES} "${line}"
+	${COLOR} CYAN
+	printf ' %4d: Skiping: ' ${N_LINES}
+     	${COLOR} RED
+	printf '\"%s\"\n' "${line}"
 	${COLOR} reset
     fi
     if [[ ${N_ERROR} -ne 0 ]]; then 
@@ -87,13 +95,14 @@ do
 done < "${1:-/dev/stdin}"
 #
 ${COLOR} GREEN
-if [[ ${SKIP_LINES} -ne 0 ]]; then 
-    printf '\nNumber of lines skipped: '
+if [[ ${START_LINE} -gt 1 ]]; then 
+    printf '\n Input Lines Skipped: '
     ${COLOR} YELLOW
-    printf '%d\n' ${SKIP_LINES}
+    let START_LINE-=1
+    printf '%d to %d\n' ${START_LINE_MIN} ${START_LINE}
 fi
 ${COLOR} GREEN
-printf 'Number of lines processed: '
+printf 'Total Input lines: '
 ${COLOR} YELLOW
 printf '%d\n' ${N_LINES}
 
